import { describe, expect, it } from 'vitest';
import { attributesForPatterns } from '../src/policy';

describe('sync policy', () => {
  it('updates the managed attributes block without deleting custom rules', () => {
    const existing = [
      '*.drawio binary',
      '# BEGIN GITHUB VAULT SYNC',
      '*.old filter=lfs diff=lfs merge=lfs -text',
      '# END GITHUB VAULT SYNC',
      '*.custom text eol=lf'
    ].join('\n');
    const result = attributesForPatterns(['**/*.png'], existing);

    expect(result).toContain('*.drawio binary');
    expect(result).toContain('*.custom text eol=lf');
    expect(result).toContain('**/*.png filter=lfs diff=lfs merge=lfs -text');
    expect(result).not.toContain('*.old filter=lfs diff=lfs merge=lfs -text');
    expect(result.match(/BEGIN GITHUB VAULT SYNC/g)).toHaveLength(1);
  });

  it('migrates the old generated format once', () => {
    const old = [
      '# Generated by GitHub Vault Sync. Manual additions are preserved only if they are outside this block.',
      '* text=auto',
      '*.md text eol=lf',
      '*.custom text eol=lf'
    ].join('\n');
    const result = attributesForPatterns(['*.png'], old);

    expect(result).toContain('*.custom text eol=lf');
    expect(result).toContain('*.png filter=lfs diff=lfs merge=lfs -text');
    expect(result).toContain('# BEGIN GITHUB VAULT SYNC');
  });
});

it('keeps every plugin data.json local even if the editable exclude list is empty', async () => {
  const { localExcludeEntries } = await import('../src/policy');
  const { DEFAULT_SETTINGS } = await import('../src/types');
  const entries = localExcludeEntries({ ...DEFAULT_SETTINGS, includeObsidian: true, excludePatterns: [] });
  expect(entries).toContain('.obsidian/plugins/**/data.json');
  expect(entries).toContain('.obsidian/plugins/github-vault-sync/data.json');
});

it('ignores the directory entry as well as children of an excluded embedded repository', async () => {
  const { localExcludeEntries } = await import('../src/policy');
  const { DEFAULT_SETTINGS } = await import('../src/types');
  const entries = localExcludeEntries({ ...DEFAULT_SETTINGS,
    excludePatterns: ['.obsidian/plugins/embedded/**'] });
  expect(entries).toContain('.obsidian/plugins/embedded/**');
  expect(entries).toContain('.obsidian/plugins/embedded/');
});
