import { promises as fs } from 'node:fs';
import path from 'node:path';
import { DEFAULT_EXCLUDE_PATTERNS, GIT_ATTRIBUTES, GithubVaultSyncSettings, SYNC_MANIFEST } from './types';
import { createSyncManifest, ensureDirectory, getManifestPath, isSafeRelativePath, normalizeRelPath, writeJsonFile } from './utils';

const GENERATED_START = '# BEGIN GITHUB VAULT SYNC';
const GENERATED_END = '# END GITHUB VAULT SYNC';
const TEXT_ATTRIBUTE_LINES = [
  '* text=auto',
  '*.md text eol=lf',
  '*.markdown text eol=lf',
  '*.json text eol=lf',
  '*.yaml text eol=lf',
  '*.yml text eol=lf',
  '*.css text eol=lf',
  '*.js text eol=lf',
  '*.ts text eol=lf',
  '*.mjs text eol=lf',
  '*.cjs text eol=lf',
  '*.txt text eol=lf'
];

function generatedBlock(patterns: string[]): string[] {
  return [
    GENERATED_START,
    '# Generated by GitHub Vault Sync.',
    ...TEXT_ATTRIBUTE_LINES,
    ...patterns.map((pattern) => `${normalizeRelPath(pattern)} filter=lfs diff=lfs merge=lfs -text`),
    GENERATED_END
  ];
}

function isLegacyGeneratedLine(line: string): boolean {
  return line === '# Generated by GitHub Vault Sync. Manual additions are preserved only if they are outside this block.'
    || TEXT_ATTRIBUTE_LINES.includes(line);
}

/**
 * Return the managed .gitattributes block while preserving user rules outside it.
 * The optional existing content is used by writeSyncPolicy to update rules in place.
 */
export function attributesForPatterns(patterns: string[], existing = ''): string {
  const nextBlock = generatedBlock(patterns);
  const existingLines = existing.replace(/\r\n/g, '\n').split('\n');
  while (existingLines.length && existingLines[existingLines.length - 1] === '') existingLines.pop();

  const start = existingLines.indexOf(GENERATED_START);
  const end = start >= 0 ? existingLines.indexOf(GENERATED_END, start + 1) : -1;
  if (start >= 0 && end >= start) {
    const merged = [...existingLines.slice(0, start), ...nextBlock, ...existingLines.slice(end + 1)];
    return `${merged.join('\n').replace(/\n+$/, '')}\n`;
  }

  // Migrate the pre-marker format without duplicating the plugin's old rules.
  const preserved = existingLines.filter((line) => !isLegacyGeneratedLine(line));
  const merged = [...preserved, ...(preserved.length ? [''] : []), ...nextBlock];
  return `${merged.join('\n')}\n`;
}

export async function writeSyncPolicy(vaultPath: string, settings: GithubVaultSyncSettings): Promise<void> {
  const manifestPath = getManifestPath(vaultPath);
  await writeJsonFile(manifestPath, createSyncManifest(settings));
  const attributesPath = path.join(vaultPath, GIT_ATTRIBUTES);
  let existing = '';
  try {
    existing = await fs.readFile(attributesPath, 'utf8');
  } catch {
    // The file is created below when it does not exist.
  }
  await fs.writeFile(attributesPath, attributesForPatterns(settings.lfsPatterns, existing), 'utf8');
}

export async function readSyncPolicy(vaultPath: string): Promise<ReturnType<typeof createSyncManifest> | null> {
  try {
    const content = await fs.readFile(path.join(vaultPath, SYNC_MANIFEST), 'utf8');
    return JSON.parse(content) as ReturnType<typeof createSyncManifest>;
  } catch {
    return null;
  }
}

export function localExcludeEntries(settings: GithubVaultSyncSettings): string[] {
  const patterns = [
    '.git/',
    '.trash/',
    ...DEFAULT_EXCLUDE_PATTERNS,
    ...(settings.includeObsidian ? [] : ['.obsidian/']),
    ...settings.excludePatterns
  ];
  // Git treats an embedded repository as one untracked directory. `dir/**`
  // excludes its files, but does not hide the directory entry from `git status`.
  return [...new Set(patterns.flatMap((pattern) => pattern.endsWith('/**')
    ? [pattern, `${pattern.slice(0, -3)}/`] : [pattern]))];
}

export async function ensureConflictDirectory(vaultPath: string, settings: GithubVaultSyncSettings, sessionFolder: string): Promise<string> {
  if (!isSafeRelativePath(settings.conflictFolder) || !isSafeRelativePath(sessionFolder)) {
    throw new Error('Conflict backup folder must remain inside the vault');
  }
  const folder = path.join(vaultPath, settings.conflictFolder, sessionFolder);
  await ensureDirectory(folder);
  return folder;
}
